# Defining the Final State Machine.
FSM = {
    ("ANY", "goodbye") : "GOODBYE",
    ("ANY", "good") : "POSITIVE",
    ("ANY", "happy") : "POSITIVE",
    ("ANY", "thank_you") : "YOU_ARE_WELCOME",
    ("ANY", "greeting") : "GREETING",
    ("ANY", "angry") : "NEGATIVE",
    ("ANY", "tired") : "USER_IS_TIRED",
    ("ANY", "get_goal_progress") : "GET_PROGRESS",
    ("ANY", "how_to_make_exercises[NOUNS]") : "GET_VIDEO",
    ("ANY", "get_exercise[DATE]") : "GET_EXERCISE",
    ("ANY", "get_exercise") : "ASK_FOR_DATE_OF_EXERCISE",
    ("ANY", "get_meals") : "ASK_FOR_DATE_OF_MEALS",
    ("ANY", "get_meals[DATE]") : "GET_MEALS",
    ("ASK_FOR_DATE_OF_EXERCISE", "[DATE]") : "GET_EXERCISE",
    ("ASK_FOR_DATE_OF_MEALS", "[DATE]") : "GET_MEALS",
    ("ANY" , "update_parameters[CARDINAL&NOUNS]") : "UPDATE_PARAMETERS",
    ("ANY" , "update_parameters[CARDINAL]") : "WHAT_PARAMETER_TO_UPDATE",
    ("ANY" , "update_parameters[NOUNS]") : "TO_WHAT_VALUE_TO_UPDATE",
    ("ANY" , "update_parameters") : "ASK_WHAT_PARAMETERS_AND_TO_WHAT_VALUE_TO_UPDATE",
    ("WHAT_PARAMETER_TO_UPDATE", "[NOUNS]") : "UPDATE_PARAMETERS",
    ("TO_WHAT_VALUE_TO_UPDATE", "[CARDINAL]") : "UPDATE_PARAMETERS",
    ("ASK_WHAT_PARAMETERS_AND_TO_WHAT_VALUE_TO_UPDATE", "[CARDINAL&NOUNS]") : "UPDATE_PARAMETERS",
    ("ASK_WHAT_PARAMETERS_AND_TO_WHAT_VALUE_TO_UPDATE", "[CARDINAL]") : "WHAT_PARAMETER_TO_UPDATE",
    ("ASK_WHAT_PARAMETERS_AND_TO_WHAT_VALUE_TO_UPDATE", "[NOUNS]") : "TO_WHAT_VALUE_TO_UPDATE",
    ("TO_WHAT_VALUE_TO_UPDATE", "[NOUNS]") : "TO_WHAT_VALUE_TO_UPDATE",
    ("ANY", "get_stats") : "GET_STATS",
    ("ANY", "kcals_burned[DATE]") : "KCALS_BURNED",
    ("ANY", "kcals_burned") : "ASK_FOR_WHAT_DATE_KCALS_BURNED",
    ("ASK_FOR_WHAT_DATE_KCALS_BURNED", "[DATE]") : "KCALS_BURNED",
    ("ANY", "kcals_gained[DATE]") : "KCALS_GAINED",
    ("ANY", "kcals_gained") : "ASK_FOR_WHAT_DATE_KCALS_GAINED",
    ("ASK_FOR_WHAT_DATE_KCALS_GAINED", "[DATE]") : "KCALS_GAINED",
    ("ANY", "oos") : "SEQUENCE2SEQUENCE",
    ("ANY", "yes") : "ASK_WHAT_USER_MEAN",
    ("ANY", "no") : "ASK_WHAT_USER_MEAN"
}